name: Approve PR and delete branch
on: pull_request_target

env:
  PR_BRANCH: release-ci-${{ github.sha }}

jobs:
  approve_pr_branch:
    name: Approve PR branch
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: echo "2.0 automerge start = ${{ env.PR_BRANCH }}"
      - uses: hmarr/auto-approve-action@v4
      - run: echo "2.1 automerge end"


  merge_pr_branch:
    name: Merge PR branch
    needs: approve_pr_branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge Changelog PR
        run: |
          gh pr merge --squash --auto --delete-branch ${{ env.PR_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
